"""add_account_models

Revision ID: 4910b527999c
Revises: b70eedcfc443
Create Date: 2025-12-23 10:58:21.633546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4910b527999c'
down_revision = 'b70eedcfc443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('api_secret', sa.String(length=64), nullable=True),
    sa.Column('google_client_id', sa.String(length=255), nullable=True),
    sa.Column('google_client_secret', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('max_concurrent_bots', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_api_key'), 'accounts', ['api_key'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('account_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_user_id', name='_account_external_user_uc')
    )
    op.create_index('ix_account_user_account_external', 'account_users', ['account_id', 'external_user_id'], unique=False)
    op.create_index(op.f('ix_account_users_account_id'), 'account_users', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_users_id'), 'account_users', ['id'], unique=False)
    op.create_table('account_user_google_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_user_id', sa.Integer(), nullable=False),
    sa.Column('google_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_join_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_google_integrations_account_user_id'), 'account_user_google_integrations', ['account_user_id'], unique=True)
    op.create_index(op.f('ix_account_user_google_integrations_id'), 'account_user_google_integrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_google_integrations_id'), table_name='account_user_google_integrations')
    op.drop_index(op.f('ix_account_user_google_integrations_account_user_id'), table_name='account_user_google_integrations')
    op.drop_table('account_user_google_integrations')
    op.drop_index(op.f('ix_account_users_id'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_account_id'), table_name='account_users')
    op.drop_index('ix_account_user_account_external', table_name='account_users')
    op.drop_table('account_users')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_api_key'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ### 