"""add_bot_settings

Revision ID: 9063af59d4e3
Revises: cc50d539a0db
Create Date: 2025-12-23 15:39:15.435406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9063af59d4e3'
down_revision = 'cc50d539a0db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user_google_integrations', sa.Column('bot_name', sa.String(length=100), nullable=True))
    op.add_column('account_user_google_integrations', sa.Column('auto_join_mode', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_user_google_integrations', 'auto_join_mode')
    op.drop_column('account_user_google_integrations', 'bot_name')
    # ### end Alembic commands ### 