"""add_account_id_to_meeting

Revision ID: cc50d539a0db
Revises: 4910b527999c
Create Date: 2025-12-23 11:30:46.846762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc50d539a0db'
down_revision = '4910b527999c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('account_id', sa.Integer(), nullable=True))
    op.alter_column('meetings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_meeting_account_platform_native_id_created_at', 'meetings', ['account_id', 'platform', 'platform_specific_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_meetings_account_id'), 'meetings', ['account_id'], unique=False)
    op.create_foreign_key(None, 'meetings', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index(op.f('ix_meetings_account_id'), table_name='meetings')
    op.drop_index('ix_meeting_account_platform_native_id_created_at', table_name='meetings')
    op.alter_column('meetings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('meetings', 'account_id')
    # ### end Alembic commands ### 